# oracle/generate_seed.py
#
# Generates oracle/seed_data.sql with realistic e-commerce data.
# Run once during development: python oracle/generate_seed.py
# Then execute the output: seed_data.sql in SQL*Plus as oraclechat user.

import random
from datetime import datetime, timedelta
from faker import Faker

fake = Faker()
random.seed(42)      # Fixed seed = reproducible data across runs
Faker.seed(42)       # Same for Faker

# ── Volume constants ───────────────────────────────────────────
N_CUSTOMERS = 200
N_PRODUCTS  = 50
N_ORDERS    = 500

# ── Business domain data ───────────────────────────────────────
# Moroccan cities make the demo feel real and locally grounded.
# Recruiters notice details like this.
CITIES = [
    "Casablanca", "Rabat", "Marrakech", "Fes", "Tangier",
    "Agadir", "Meknes", "Oujda", "Kenitra", "Tetouan"
]

CATEGORIES = {
    "Electronics":   [
        ("Laptop Pro 15", 8999), ("Wireless Headphones", 799),
        ("Smartphone X12", 5499), ("USB-C Hub", 299),
        ("Mechanical Keyboard", 649), ("4K Monitor", 3299),
        ("Webcam HD", 449), ("External SSD 1TB", 899),
        ("Smart Watch", 1299), ("Bluetooth Speaker", 549),
    ],
    "Books": [
        ("Oracle 19c Complete Guide", 299), ("Python Crash Course", 189),
        ("Clean Code", 229), ("Designing Data-Intensive Apps", 349),
        ("The Pragmatic Programmer", 219), ("Docker Deep Dive", 179),
        ("SQL Performance Explained", 259), ("Linux Bible", 319),
        ("Cloud Architecture Patterns", 289), ("Git Pro", 149),
    ],
    "Clothing": [
        ("Djellaba Traditional", 450), ("Leather Babouche", 280),
        ("Cotton T-Shirt", 89), ("Denim Jacket", 399),
        ("Sports Hoodie", 229), ("Formal Shirt", 199),
        ("Running Shoes", 699), ("Casual Sneakers", 499),
        ("Winter Coat", 899), ("Silk Scarf", 189),
    ],
    "Home and Kitchen": [
        ("Tagine Ceramic Set", 349), ("Argan Oil 500ml", 199),
        ("Coffee Maker", 599), ("Air Fryer XL", 899),
        ("Blender Pro", 449), ("Bedsheet Set King", 299),
        ("LED Desk Lamp", 179), ("Storage Ottoman", 549),
        ("Wall Clock Modern", 149), ("Candle Set Luxury", 129),
    ],
    "Sports": [
        ("Yoga Mat Premium", 249), ("Resistance Bands Set", 129),
        ("Football Size 5", 189), ("Tennis Racket Pro", 599),
        ("Cycling Helmet", 349), ("Swimming Goggles", 99),
        ("Dumbbell Set 20kg", 799), ("Jump Rope Speed", 79),
        ("Basketball Indoor", 229), ("Badminton Set", 159),
    ],
    "Beauty": [
        ("Argan Hair Oil", 149), ("Rose Water Toner", 89),
        ("Vitamin C Serum", 199), ("Moisturizer SPF50", 179),
        ("Lipstick Set 6pc", 129), ("Perfume Oud 50ml", 599),
        ("Micellar Water", 79), ("Eye Cream Premium", 249),
        ("Sunscreen SPF30", 99), ("Face Mask Clay", 69),
    ],
}

ORDER_STATUSES = ["PENDING","CONFIRMED","SHIPPED","DELIVERED","DELIVERED","DELIVERED","CANCELLED","RETURNED"]
# DELIVERED appears 3x intentionally — most orders complete successfully
PAYMENT_METHODS = ["CREDIT_CARD","DEBIT_CARD","BANK_TRANSFER","CASH_ON_DELIVERY","MOBILE_PAYMENT"]
PAYMENT_WEIGHTS = [30, 25, 20, 15, 10]  # % distribution — realistic for Morocco


def oracle_date(dt: datetime) -> str:
    """Oracle TO_DATE literal from a Python datetime."""
    return f"TO_DATE('{dt.strftime('%Y-%m-%d')}','YYYY-MM-DD')"


def escape(s: str) -> str:
    """Escape single quotes for Oracle SQL strings."""
    return s.replace("'", "''")


lines = []
lines.append("-- ============================================================")
lines.append("-- OracleChat seed data — generated by oracle/generate_seed.py")
lines.append(f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
lines.append("-- Run as: oraclechat user connected to ORCLPDB")
lines.append("-- ============================================================")
lines.append("")


# ── CUSTOMERS ─────────────────────────────────────────────────
lines.append("-- CUSTOMERS")
customer_ids = list(range(1, N_CUSTOMERS + 1))

for cid in customer_ids:
    first  = escape(fake.first_name())
    last   = escape(fake.last_name())
    # Unique email: firstname.lastname.cid avoids collisions
    email  = f"{first.lower()}.{last.lower()}.{cid}@{fake.free_email_domain()}"
    phone  = f"+212{random.randint(600000000, 699999999)}"
    city   = random.choice(CITIES)
    reg_dt = oracle_date(
        datetime(2022, 1, 1) + timedelta(days=random.randint(0, 700))
    )
    # 92% active, 6% inactive, 2% banned — realistic distribution
    status = random.choices(["ACTIVE","INACTIVE","BANNED"], weights=[92,6,2])[0]

    lines.append(
        f"INSERT INTO customers (customer_id,first_name,last_name,email,"
        f"phone,city,country,registration_date,status) VALUES ("
        f"{cid},'{first}','{last}','{email}',"
        f"'{phone}','{city}','Morocco',{reg_dt},'{status}');"
    )

lines.append("")


# ── PRODUCTS ──────────────────────────────────────────────────
lines.append("-- PRODUCTS")
product_ids = list(range(1, N_PRODUCTS + 1))
products    = []  # [(product_id, unit_price), ...] — needed for order items

pid = 1
for category, items in CATEGORIES.items():
    for name, base_price in items:
        # Add slight price variance so data isn't perfectly uniform
        price  = round(base_price * random.uniform(0.9, 1.1), 2)
        stock  = random.randint(0, 200)
        status = "DISCONTINUED" if random.random() < 0.08 else "ACTIVE"

        lines.append(
            f"INSERT INTO products (product_id,name,category,unit_price,"
            f"stock_quantity,status) VALUES ("
            f"{pid},'{escape(name)}','{category}',{price},{stock},'{status}');"
        )
        products.append((pid, price))
        pid += 1

lines.append("")


# ── ORDERS + ORDER_ITEMS + PAYMENTS ───────────────────────────
# We generate these together because order total depends on items,
# and payment amount depends on order total.
lines.append("-- ORDERS, ORDER_ITEMS, PAYMENTS")

order_id   = 1
item_id    = 1
payment_id = 1

# Spread orders from Jan 2023 to Jun 2024 — gives monthly trend data
order_start = datetime(2023, 1, 1)
order_end   = datetime(2024, 6, 30)
date_range  = (order_end - order_start).days

for _ in range(N_ORDERS):
    cid        = random.choice(customer_ids)
    order_date = order_start + timedelta(days=random.randint(0, date_range))
    status     = random.choice(ORDER_STATUSES)
    city       = random.choice(CITIES)
    address    = escape(f"{random.randint(1,200)} {fake.street_name()}, {city}")

    # Pick 1–4 distinct products per order
    n_items       = random.randint(1, 4)
    chosen        = random.sample(products, n_items)
    order_total   = 0
    item_rows     = []

    for (prod_id, unit_price) in chosen:
        qty        = random.randint(1, 3)
        line_total = round(qty * unit_price, 2)
        order_total += line_total

        item_rows.append(
            f"INSERT INTO order_items (item_id,order_id,product_id,quantity,"
            f"unit_price,line_total) VALUES ("
            f"{item_id},{order_id},{prod_id},{qty},{unit_price},{line_total});"
        )
        item_id += 1

    order_total = round(order_total, 2)
    order_dt    = oracle_date(order_date)

    lines.append(
        f"INSERT INTO orders (order_id,customer_id,order_date,status,"
        f"total_amount,shipping_address) VALUES ("
        f"{order_id},{cid},{order_dt},'{status}',"
        f"{order_total},'{address}');"
    )

    lines.extend(item_rows)

    # Payment: only non-PENDING, non-CANCELLED orders have payments
    if status not in ("PENDING", "CANCELLED"):
        # Payment happens 0–3 days after order
        pay_date   = oracle_date(order_date + timedelta(days=random.randint(0, 3)))
        method     = random.choices(PAYMENT_METHODS, weights=PAYMENT_WEIGHTS)[0]

        # RETURNED orders have a REFUNDED payment
        if status == "RETURNED":
            pay_status = "REFUNDED"
        else:
            # 95% complete, 5% still pending (processing delay)
            pay_status = random.choices(["COMPLETED","PENDING"], weights=[95,5])[0]

        lines.append(
            f"INSERT INTO payments (payment_id,order_id,payment_date,amount,"
            f"method,status) VALUES ("
            f"{payment_id},{order_id},{pay_date},{order_total},"
            f"'{method}','{pay_status}');"
        )
        payment_id += 1

    order_id += 1
    lines.append("")

lines.append("COMMIT;")
lines.append("")
lines.append(f"-- Totals: {N_CUSTOMERS} customers, {N_PRODUCTS} products,")
lines.append(f"-- {N_ORDERS} orders, ~{item_id-1} order items, ~{payment_id-1} payments")


# ── Write output ───────────────────────────────────────────────
output_path = "oracle/seed_data.sql"
with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"✅ Generated {output_path}")
print(f"   Customers : {N_CUSTOMERS}")
print(f"   Products  : {N_PRODUCTS}")
print(f"   Orders    : {N_ORDERS}")
print(f"   Items     : ~{item_id - 1}")
print(f"   Payments  : ~{payment_id - 1}")